default_language_version:
  python: python3.6
repos:
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
    args: ["-l", "119", "-t", "py36"]
    require_serial: true
- repo: https://gitlab.com/pycqa/flake8
  rev: "3.7.9"
  hooks:
  - id: flake8
    require_serial: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
